apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  labels:
    app: helloworld
spec:
  replicas: 2  # Number of instances
  strategy:
    type: RollingUpdate  # Ensures zero-downtime deployments
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      restartPolicy: Always
      containers:
        - name: helloworld
          image: saicharan6771/helloworld:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"  # Limit CPU usage
              memory: "512Mi"  # Limit memory usage
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
