apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: eaglebird
        image: saicharan6771/eaglebird:latest  # Ensure it's the correct image
        ports:
        - containerPort: 8080
