apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Port exposed inside the cluster
      targetPort: 8080 # Port on the container
      nodePort: 30080  # External port accessible on worker nodes (must be between 30000-32767)
